function Hd = FDAToolOutput_ACheby2LowpassFilter
%UNTITLED Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the DSP System Toolbox 9.1.
% Generated on: 29-Aug-2018 21:13:30

% Chebyshev Type II Lowpass filter designed using FDESIGN.LOWPASS.

global sosM;
global sV;

% All frequency values are in Hz.
Fs = 8000;  % Sampling Frequency

Fpass = 140;         % Passband Frequency
Fstop = 180;         % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 80;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'cheby2', 'MatchExactly', match);

sosM = Hd.sosMatrix; sV = Hd.ScaleValues;
end
